version: 1.0.{build}

image: Visual Studio 2017
platform: x64
configuration: Debug

clone_folder: c:\projects\DirectXShaderCompiler
clone_depth: 1

environment:
  HLSL_SRC_DIR: c:\projects\DirectXShaderCompiler
  HLSL_BLD_DIR: c:\projects\DirectXShaderCompiler\build

install:
- cmd: git submodule update --init

before_build:
- cmd: call utils\hct\hctstart %HLSL_SRC_DIR% %HLSL_BLD_DIR%

build_script:
- cmd: call utils\hct\hctbuild -%PLATFORM% -%CONFIGURATION% -vs2017 -spirvtest

test_script:
- ps:  utils\appveyor\appveyor_test.ps1
- cmd: call utils\hct\hcttest spirv_only

after_test:
- cmd: cd build\%CONFIGURATION%\bin
- cmd: 7z a artifacts.zip d*.exe d*.dll HLSLHost.exe

artifacts:
- path: build\$(configuration)\bin\artifacts.zip

notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
